import type { SizeCategory } from './breed.model'

export interface BreedSeedData {
  name: string
  nameEn: string
  fciGroup: number
  sizeCategory: SizeCategory
}

/**
 * Каталог пород FCI (польские названия по номенклатуре ZKwP).
 * Сидируется через upsert по `name` — существующие записи не перезаписываются,
 * поэтому список можно безопасно дополнять.
 */
export const BREEDS_DATA: BreedSeedData[] = [
  // ============================================================
  // Grupa 1 — Owczarki i inne psy pasterskie
  // ============================================================
  { name: 'Owczarek Niemiecki', nameEn: 'German Shepherd', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Biały Owczarek Szwajcarski', nameEn: 'White Swiss Shepherd Dog', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Border Collie', nameEn: 'Border Collie', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Corgi', nameEn: 'Welsh Corgi', fciGroup: 1, sizeCategory: 'small' },
  { name: 'Welsh Corgi Cardigan', nameEn: 'Welsh Corgi Cardigan', fciGroup: 1, sizeCategory: 'small' },
  { name: 'Owczarek Australijski', nameEn: 'Australian Shepherd', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Owczarek Belgijski', nameEn: 'Belgian Shepherd Dog', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Owczarek Szkocki Długowłosy', nameEn: 'Rough Collie', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Owczarek Szkocki Krótkowłosy', nameEn: 'Smooth Collie', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Owczarek Szetlandzki', nameEn: 'Shetland Sheepdog', fciGroup: 1, sizeCategory: 'small' },
  { name: 'Bearded Collie', nameEn: 'Bearded Collie', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Owczarek Staroangielski (Bobtail)', nameEn: 'Old English Sheepdog', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Briard (Owczarek Francuski Długowłosy)', nameEn: 'Briard', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Beauceron', nameEn: 'Beauceron', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Owczarek Pikardyjski', nameEn: 'Picardy Sheepdog', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Owczarek Holenderski', nameEn: 'Dutch Shepherd', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Polski Owczarek Nizinny', nameEn: 'Polish Lowland Sheepdog', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Polski Owczarek Podhalański', nameEn: 'Tatra Shepherd Dog', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Puli', nameEn: 'Puli', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Pumi', nameEn: 'Pumi', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Mudi', nameEn: 'Mudi', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Komondor', nameEn: 'Komondor', fciGroup: 1, sizeCategory: 'giant' },
  { name: 'Kuvasz', nameEn: 'Kuvasz', fciGroup: 1, sizeCategory: 'giant' },
  { name: 'Czechosłowacki Wilczak', nameEn: 'Czechoslovakian Wolfdog', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Wilczak Saarloosa', nameEn: 'Saarloos Wolfdog', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Schipperke', nameEn: 'Schipperke', fciGroup: 1, sizeCategory: 'small' },
  { name: 'Australian Cattle Dog', nameEn: 'Australian Cattle Dog', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Australian Kelpie', nameEn: 'Australian Kelpie', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Owczarek Maremmański', nameEn: 'Maremma and Abruzzes Sheepdog', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Owczarek Pirenejski Długowłosy', nameEn: 'Long-haired Pyrenean Sheepdog', fciGroup: 1, sizeCategory: 'small' },
  { name: 'Owczarek Kataloński', nameEn: 'Catalan Sheepdog', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Owczarek Chorwacki', nameEn: 'Croatian Shepherd Dog', fciGroup: 1, sizeCategory: 'medium' },
  { name: 'Owczarek Rumuński Mioritic', nameEn: 'Romanian Mioritic Shepherd Dog', fciGroup: 1, sizeCategory: 'giant' },
  { name: 'Owczarek Rumuński Karpacki', nameEn: 'Romanian Carpathian Shepherd Dog', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Lancashire Heeler', nameEn: 'Lancashire Heeler', fciGroup: 1, sizeCategory: 'small' },
  { name: 'Owczarek Bergamski', nameEn: 'Bergamasco Shepherd', fciGroup: 1, sizeCategory: 'large' },
  { name: 'Bouvier des Flandres', nameEn: 'Bouvier des Flandres', fciGroup: 1, sizeCategory: 'large' },

  // ============================================================
  // Grupa 2 — Pinczery, sznaucery, molosy i szwajcarskie psy pasterskie
  // ============================================================
  { name: 'Doberman', nameEn: 'Dobermann', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Pinczer Średni', nameEn: 'German Pinscher', fciGroup: 2, sizeCategory: 'medium' },
  { name: 'Pinczer Miniaturowy', nameEn: 'Miniature Pinscher', fciGroup: 2, sizeCategory: 'small' },
  { name: 'Affenpinczer', nameEn: 'Affenpinscher', fciGroup: 2, sizeCategory: 'small' },
  { name: 'Sznaucer Olbrzym', nameEn: 'Giant Schnauzer', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Sznaucer Średni', nameEn: 'Standard Schnauzer', fciGroup: 2, sizeCategory: 'medium' },
  { name: 'Sznaucer Miniaturowy', nameEn: 'Miniature Schnauzer', fciGroup: 2, sizeCategory: 'small' },
  { name: 'Czarny Terier Rosyjski', nameEn: 'Black Russian Terrier', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Bokser', nameEn: 'German Boxer', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Rottweiler', nameEn: 'Rottweiler', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Dog Niemiecki', nameEn: 'Great Dane', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Buldog Angielski', nameEn: 'English Bulldog', fciGroup: 2, sizeCategory: 'medium' },
  { name: 'Bulmastif', nameEn: 'Bullmastiff', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Mastif Angielski', nameEn: 'English Mastiff', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Mastif Neapolitański', nameEn: 'Neapolitan Mastiff', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Mastif Hiszpański', nameEn: 'Spanish Mastiff', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Mastif Pirenejski', nameEn: 'Pyrenean Mastiff', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Mastif Tybetański', nameEn: 'Tibetan Mastiff', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Dog z Bordeaux', nameEn: 'Dogue de Bordeaux', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Cane Corso', nameEn: 'Italian Cane Corso', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Bernardyn', nameEn: 'Saint Bernard', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Nowofundland', nameEn: 'Newfoundland', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Leonberger', nameEn: 'Leonberger', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Landseer', nameEn: 'Landseer', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Hovawart', nameEn: 'Hovawart', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Berneński Pies Pasterski', nameEn: 'Bernese Mountain Dog', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Duży Szwajcarski Pies Pasterski', nameEn: 'Greater Swiss Mountain Dog', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Appenzeller', nameEn: 'Appenzell Cattle Dog', fciGroup: 2, sizeCategory: 'medium' },
  { name: 'Entlebucher', nameEn: 'Entlebuch Cattle Dog', fciGroup: 2, sizeCategory: 'medium' },
  { name: 'Owczarek Kaukaski', nameEn: 'Caucasian Shepherd Dog', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Owczarek Środkowoazjatycki', nameEn: 'Central Asia Shepherd Dog', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Owczarek Anatolijski (Kangal)', nameEn: 'Kangal Shepherd Dog', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Owczarek Szarplaniński', nameEn: 'Sarplaninac', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Tornjak', nameEn: 'Tornjak', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Tosa', nameEn: 'Tosa Inu', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Shar Pei', nameEn: 'Shar Pei', fciGroup: 2, sizeCategory: 'medium' },
  { name: 'Broholmer', nameEn: 'Broholmer', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Dog Argentyński', nameEn: 'Dogo Argentino', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Dogo Canario', nameEn: 'Presa Canario', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Ca de Bou', nameEn: 'Majorca Mastiff', fciGroup: 2, sizeCategory: 'large' },
  { name: 'Fila Brasileiro', nameEn: 'Fila Brasileiro', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Pirenejski Pies Górski', nameEn: 'Pyrenean Mountain Dog', fciGroup: 2, sizeCategory: 'giant' },
  { name: 'Pies Górski z Estreli', nameEn: 'Estrela Mountain Dog', fciGroup: 2, sizeCategory: 'giant' },

  // ============================================================
  // Grupa 3 — Teriery
  // ============================================================
  { name: 'Airedale Terrier', nameEn: 'Airedale Terrier', fciGroup: 3, sizeCategory: 'medium' },
  { name: 'Bedlington Terrier', nameEn: 'Bedlington Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Border Terrier', nameEn: 'Border Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Foksterier Krótkowłosy', nameEn: 'Smooth Fox Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Foksterier Szorstkowłosy', nameEn: 'Wire Fox Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Lakeland Terrier', nameEn: 'Lakeland Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Manchester Terrier', nameEn: 'Manchester Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Terier Walijski', nameEn: 'Welsh Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Terier Irlandzki', nameEn: 'Irish Terrier', fciGroup: 3, sizeCategory: 'medium' },
  { name: 'Kerry Blue Terrier', nameEn: 'Kerry Blue Terrier', fciGroup: 3, sizeCategory: 'medium' },
  { name: 'Irlandzki Terier Pszeniczny', nameEn: 'Irish Soft Coated Wheaten Terrier', fciGroup: 3, sizeCategory: 'medium' },
  { name: 'Glen of Imaal Terrier', nameEn: 'Irish Glen of Imaal Terrier', fciGroup: 3, sizeCategory: 'medium' },
  { name: 'Cairn Terrier', nameEn: 'Cairn Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'West Highland White Terrier', nameEn: 'West Highland White Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Terier Szkocki', nameEn: 'Scottish Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Sealyham Terrier', nameEn: 'Sealyham Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Skye Terrier', nameEn: 'Skye Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Norfolk Terrier', nameEn: 'Norfolk Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Norwich Terrier', nameEn: 'Norwich Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Dandie Dinmont Terrier', nameEn: 'Dandie Dinmont Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Terier Australijski', nameEn: 'Australian Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Silky Terrier', nameEn: 'Australian Silky Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Yorkshire Terrier', nameEn: 'Yorkshire Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Staffordshire Bull Terrier', nameEn: 'Staffordshire Bull Terrier', fciGroup: 3, sizeCategory: 'medium' },
  { name: 'Amerykański Staffordshire Terrier', nameEn: 'American Staffordshire Terrier', fciGroup: 3, sizeCategory: 'medium' },
  { name: 'Bulterier', nameEn: 'Bull Terrier', fciGroup: 3, sizeCategory: 'medium' },
  { name: 'Bulterier Miniaturowy', nameEn: 'Miniature Bull Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Parson Russell Terrier', nameEn: 'Parson Russell Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Jack Russell Terrier', nameEn: 'Jack Russell Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Terier Czeski', nameEn: 'Cesky Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'Niemiecki Terier Myśliwski (Jagdterrier)', nameEn: 'German Hunting Terrier', fciGroup: 3, sizeCategory: 'small' },
  { name: 'English Toy Terrier', nameEn: 'English Toy Terrier', fciGroup: 3, sizeCategory: 'small' },

  // ============================================================
  // Grupa 4 — Jamniki
  // ============================================================
  { name: 'Jamnik', nameEn: 'Dachshund', fciGroup: 4, sizeCategory: 'small' },

  // ============================================================
  // Grupa 5 — Szpice i psy w typie pierwotnym
  // ============================================================
  { name: 'Husky Syberyjski', nameEn: 'Siberian Husky', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Alaskan Malamute', nameEn: 'Alaskan Malamute', fciGroup: 5, sizeCategory: 'large' },
  { name: 'Samojed', nameEn: 'Samoyed', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Pies Grenlandzki', nameEn: 'Greenland Dog', fciGroup: 5, sizeCategory: 'large' },
  { name: 'Akita', nameEn: 'Akita', fciGroup: 5, sizeCategory: 'large' },
  { name: 'Akita Amerykańska', nameEn: 'American Akita', fciGroup: 5, sizeCategory: 'large' },
  { name: 'Shiba', nameEn: 'Shiba Inu', fciGroup: 5, sizeCategory: 'small' },
  { name: 'Basenji', nameEn: 'Basenji', fciGroup: 5, sizeCategory: 'small' },
  { name: 'Chow Chow', nameEn: 'Chow Chow', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Eurasier', nameEn: 'Eurasier', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Szpic Miniaturowy (Pomeranian)', nameEn: 'Pomeranian', fciGroup: 5, sizeCategory: 'small' },
  { name: 'Szpic Niemiecki', nameEn: 'German Spitz', fciGroup: 5, sizeCategory: 'small' },
  { name: 'Szpic Wilczy (Keeshond)', nameEn: 'Keeshond', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Szpic Japoński', nameEn: 'Japanese Spitz', fciGroup: 5, sizeCategory: 'small' },
  { name: 'Szpic Fiński', nameEn: 'Finnish Spitz', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Volpino Italiano', nameEn: 'Volpino Italiano', fciGroup: 5, sizeCategory: 'small' },
  { name: 'Elkhund Szary', nameEn: 'Norwegian Elkhound Grey', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Karelski Pies na Niedźwiedzie', nameEn: 'Karelian Bear Dog', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Łajka Zachodniosyberyjska', nameEn: 'West Siberian Laika', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Łajka Wschodniosyberyjska', nameEn: 'East Siberian Laika', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Łajka Rosyjsko-Europejska', nameEn: 'Russian-European Laika', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Fiński Lapphund', nameEn: 'Finnish Lapphund', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Szwedzki Lapphund', nameEn: 'Swedish Lapphund', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Buhund Norweski', nameEn: 'Norwegian Buhund', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Islandzki Szpic Pasterski', nameEn: 'Icelandic Sheepdog', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Vallhund Szwedzki', nameEn: 'Swedish Vallhund', fciGroup: 5, sizeCategory: 'small' },
  { name: 'Cirneco dell’Etna', nameEn: 'Cirneco dell’Etna', fciGroup: 5, sizeCategory: 'small' },
  { name: 'Podenco Ibicenco', nameEn: 'Ibizan Hound', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Podenco Kanaryjski', nameEn: 'Canarian Warren Hound', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Pies Faraona', nameEn: 'Pharaoh Hound', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Podengo Portugalski', nameEn: 'Portuguese Podengo', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Thai Ridgeback', nameEn: 'Thai Ridgeback', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Xoloitzcuintle (Nagi Pies Meksykański)', nameEn: 'Xoloitzcuintle', fciGroup: 5, sizeCategory: 'medium' },
  { name: 'Peruwiański Pies Bezwłosy', nameEn: 'Peruvian Hairless Dog', fciGroup: 5, sizeCategory: 'medium' },

  // ============================================================
  // Grupa 6 — Psy gończe i rasy pokrewne
  // ============================================================
  { name: 'Beagle', nameEn: 'Beagle', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Basset Hound', nameEn: 'Basset Hound', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Pies Świętego Huberta (Bloodhound)', nameEn: 'Bloodhound', fciGroup: 6, sizeCategory: 'large' },
  { name: 'Dalmatyńczyk', nameEn: 'Dalmatian', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Rhodesian Ridgeback', nameEn: 'Rhodesian Ridgeback', fciGroup: 6, sizeCategory: 'large' },
  { name: 'Ogar Polski', nameEn: 'Polish Hound', fciGroup: 6, sizeCategory: 'large' },
  { name: 'Gończy Polski', nameEn: 'Polish Hunting Dog', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Petit Basset Griffon Vendéen', nameEn: 'Petit Basset Griffon Vendéen', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Grand Basset Griffon Vendéen', nameEn: 'Grand Basset Griffon Vendéen', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Basset Artezyjsko-Normandzki', nameEn: 'Artesian-Norman Basset', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Basset Fauve de Bretagne', nameEn: 'Fawn Brittany Basset', fciGroup: 6, sizeCategory: 'small' },
  { name: 'Foxhound Angielski', nameEn: 'English Foxhound', fciGroup: 6, sizeCategory: 'large' },
  { name: 'Foxhound Amerykański', nameEn: 'American Foxhound', fciGroup: 6, sizeCategory: 'large' },
  { name: 'Harrier', nameEn: 'Harrier', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Otterhound', nameEn: 'Otterhound', fciGroup: 6, sizeCategory: 'large' },
  { name: 'Beagle Harrier', nameEn: 'Beagle Harrier', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Posokowiec Bawarski', nameEn: 'Bavarian Mountain Scent Hound', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Posokowiec Hanowerski', nameEn: 'Hanoverian Scent Hound', fciGroup: 6, sizeCategory: 'large' },
  { name: 'Alpejski Gończy Krótkonożny', nameEn: 'Alpine Dachsbracke', fciGroup: 6, sizeCategory: 'small' },
  { name: 'Gończy Słowacki', nameEn: 'Slovakian Hound', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Segugio Italiano', nameEn: 'Italian Hound', fciGroup: 6, sizeCategory: 'medium' },
  { name: 'Black and Tan Coonhound', nameEn: 'Black and Tan Coonhound', fciGroup: 6, sizeCategory: 'large' },

  // ============================================================
  // Grupa 7 — Wyżły
  // ============================================================
  { name: 'Pointer Angielski', nameEn: 'English Pointer', fciGroup: 7, sizeCategory: 'medium' },
  { name: 'Seter Angielski', nameEn: 'English Setter', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Seter Irlandzki', nameEn: 'Irish Red Setter', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Seter Irlandzki Czerwono-Biały', nameEn: 'Irish Red and White Setter', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Seter Szkocki (Gordon)', nameEn: 'Gordon Setter', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Wyżeł Niemiecki Krótkowłosy', nameEn: 'German Shorthaired Pointer', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Wyżeł Niemiecki Szorstkowłosy', nameEn: 'German Wirehaired Pointer', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Wyżeł Niemiecki Długowłosy', nameEn: 'German Longhaired Pointer', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Wyżeł Weimarski', nameEn: 'Weimaraner', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Wyżeł Węgierski Krótkowłosy (Vizsla)', nameEn: 'Hungarian Short-haired Pointer (Vizsla)', fciGroup: 7, sizeCategory: 'medium' },
  { name: 'Wyżeł Węgierski Szorstkowłosy', nameEn: 'Hungarian Wire-haired Pointer', fciGroup: 7, sizeCategory: 'medium' },
  { name: 'Spaniel Bretoński', nameEn: 'Brittany Spaniel', fciGroup: 7, sizeCategory: 'medium' },
  { name: 'Griffon Korthalsa', nameEn: 'Wirehaired Pointing Griffon Korthals', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Mały Münsterländer', nameEn: 'Small Munsterlander', fciGroup: 7, sizeCategory: 'medium' },
  { name: 'Duży Münsterländer', nameEn: 'Large Munsterlander', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Wyżeł Włoski (Bracco Italiano)', nameEn: 'Bracco Italiano', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Spinone Italiano', nameEn: 'Spinone Italiano', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Czeski Fousek', nameEn: 'Cesky Fousek', fciGroup: 7, sizeCategory: 'large' },
  { name: 'Pudelpointer', nameEn: 'Pudelpointer', fciGroup: 7, sizeCategory: 'large' },

  // ============================================================
  // Grupa 8 — Aportery, płochacze i psy dowodne
  // ============================================================
  { name: 'Golden Retriever', nameEn: 'Golden Retriever', fciGroup: 8, sizeCategory: 'large' },
  { name: 'Labrador Retriever', nameEn: 'Labrador Retriever', fciGroup: 8, sizeCategory: 'large' },
  { name: 'Flat Coated Retriever', nameEn: 'Flat Coated Retriever', fciGroup: 8, sizeCategory: 'large' },
  { name: 'Curly Coated Retriever', nameEn: 'Curly Coated Retriever', fciGroup: 8, sizeCategory: 'large' },
  { name: 'Chesapeake Bay Retriever', nameEn: 'Chesapeake Bay Retriever', fciGroup: 8, sizeCategory: 'large' },
  { name: 'Nova Scotia Duck Tolling Retriever', nameEn: 'Nova Scotia Duck Tolling Retriever', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Cocker Spaniel', nameEn: 'Cocker Spaniel', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Cocker Spaniel Amerykański', nameEn: 'American Cocker Spaniel', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Springer Spaniel Angielski', nameEn: 'English Springer Spaniel', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Springer Spaniel Walijski', nameEn: 'Welsh Springer Spaniel', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Clumber Spaniel', nameEn: 'Clumber Spaniel', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Field Spaniel', nameEn: 'Field Spaniel', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Sussex Spaniel', nameEn: 'Sussex Spaniel', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Irlandzki Spaniel Wodny', nameEn: 'Irish Water Spaniel', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Lagotto Romagnolo', nameEn: 'Lagotto Romagnolo', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Portugalski Pies Dowodny', nameEn: 'Portuguese Water Dog', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Hiszpański Pies Dowodny', nameEn: 'Spanish Water Dog', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Kooikerhondje', nameEn: 'Nederlandse Kooikerhondje', fciGroup: 8, sizeCategory: 'small' },
  { name: 'Barbet', nameEn: 'Barbet', fciGroup: 8, sizeCategory: 'medium' },
  { name: 'Niemiecki Spaniel Myśliwski (Wachtelhund)', nameEn: 'German Spaniel', fciGroup: 8, sizeCategory: 'medium' },

  // ============================================================
  // Grupa 9 — Psy ozdobne i do towarzystwa
  // ============================================================
  { name: 'Buldog Francuski', nameEn: 'French Bulldog', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Cavalier King Charles Spaniel', nameEn: 'Cavalier King Charles Spaniel', fciGroup: 9, sizeCategory: 'small' },
  { name: 'King Charles Spaniel', nameEn: 'King Charles Spaniel', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Shih Tzu', nameEn: 'Shih Tzu', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Lhasa Apso', nameEn: 'Lhasa Apso', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Terier Tybetański', nameEn: 'Tibetan Terrier', fciGroup: 9, sizeCategory: 'medium' },
  { name: 'Spaniel Tybetański', nameEn: 'Tibetan Spaniel', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Chihuahua', nameEn: 'Chihuahua', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Maltańczyk', nameEn: 'Maltese', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Bolończyk', nameEn: 'Bolognese', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Bichon Frise', nameEn: 'Bichon Frise', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Hawańczyk', nameEn: 'Havanese', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Coton de Tuléar', nameEn: 'Coton de Tulear', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Lwi Piesek (Löwchen)', nameEn: 'Little Lion Dog', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Papillon', nameEn: 'Papillon (Continental Toy Spaniel)', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Grzywacz Chiński', nameEn: 'Chinese Crested Dog', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Pekińczyk', nameEn: 'Pekingese', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Mops', nameEn: 'Pug', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Japan Chin', nameEn: 'Japanese Chin', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Gryfonik Brukselski', nameEn: 'Griffon Bruxellois', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Gryfonik Belgijski', nameEn: 'Griffon Belge', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Petit Brabançon', nameEn: 'Petit Brabancon', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Pudel', nameEn: 'Poodle', fciGroup: 9, sizeCategory: 'medium' },
  { name: 'Rosyjski Toy', nameEn: 'Russian Toy', fciGroup: 9, sizeCategory: 'small' },
  { name: 'Boston Terrier', nameEn: 'Boston Terrier', fciGroup: 9, sizeCategory: 'small' },

  // ============================================================
  // Grupa 10 — Charty
  // ============================================================
  { name: 'Greyhound', nameEn: 'Greyhound', fciGroup: 10, sizeCategory: 'large' },
  { name: 'Whippet', nameEn: 'Whippet', fciGroup: 10, sizeCategory: 'medium' },
  { name: 'Charcik Włoski', nameEn: 'Italian Greyhound', fciGroup: 10, sizeCategory: 'small' },
  { name: 'Chart Polski', nameEn: 'Polish Greyhound', fciGroup: 10, sizeCategory: 'large' },
  { name: 'Chart Afgański', nameEn: 'Afghan Hound', fciGroup: 10, sizeCategory: 'large' },
  { name: 'Saluki', nameEn: 'Saluki', fciGroup: 10, sizeCategory: 'large' },
  { name: 'Sloughi', nameEn: 'Sloughi', fciGroup: 10, sizeCategory: 'large' },
  { name: 'Azawakh', nameEn: 'Azawakh', fciGroup: 10, sizeCategory: 'large' },
  { name: 'Borzoj (Chart Rosyjski)', nameEn: 'Borzoi', fciGroup: 10, sizeCategory: 'large' },
  { name: 'Deerhound', nameEn: 'Scottish Deerhound', fciGroup: 10, sizeCategory: 'giant' },
  { name: 'Wilczarz Irlandzki', nameEn: 'Irish Wolfhound', fciGroup: 10, sizeCategory: 'giant' },
  { name: 'Galgo Hiszpański', nameEn: 'Spanish Greyhound', fciGroup: 10, sizeCategory: 'large' },
  { name: 'Chart Węgierski (Magyar Agár)', nameEn: 'Hungarian Greyhound', fciGroup: 10, sizeCategory: 'large' },
]
